config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-puce-gar.sh
        container: qc.acc_messy-vermilion-crocodile
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-brass-zorse.sh
        container: qc.doc_grumpy-carmine-axolotl
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cinnabar-devil.sh
        container: qc.doc_flimsy-wisteria-numbat
      github.com/jkomijani/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-lavender-eel.sh
        container: qc.doc_geeky-purple-panda
      github.com/jkomijani/normflow_ restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-dandelion-mouse.sh
        container: qc.doc_flabby-white-sloth
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-viridian-shrimp.sh
        container: qc.lic_seedy-orchid-tuatara
  QC.Met:
    repos:
      github.com/jkomijani/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-flax-kakapo.sh
        container: qc.met_boozy-blue-ostrich
  QC.Sec:
    repos:
      github.com/jkomijani/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-jade-chow.sh
        container: qc.sec_ready-bronze-bandicoot
  QC.Sty:
    repos:
      github.com/jkomijani/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amaranth-cow.sh
        container: qc.sty_sleazy-bistre-fossa
  QC.Uni:
    repos:
      github.com/jkomijani/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-firebrick-labradoodle.sh
        container: qc.uni_squirrely-cardinal-capybara
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-olivine-caracal.sh
        container: qc.ver_snappy-gamboge-mau
timeout: 5400
