config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lavender-ferret.sh
        container: qc.acc_cheeky-pink-seahorse
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-chartreuse-shark.sh
        container: qc.doc_lanky-chartreuse-alligator
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sepia-tarantula.sh
        container: qc.doc_lousy-amaranth-gibbon
      github.com/jkomijani/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-green-cheetah.sh
        container: qc.doc_chewy-dandelion-deer
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-periwinkle-hummingbird.sh
        container: qc.lic_slaphappy-jade-mayfly
  QC.Met:
    repos:
      github.com/jkomijani/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-carmine-ostrich.sh
        container: qc.met_breezy-white-gharial
  QC.Sec:
    repos:
      github.com/jkomijani/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-yellow-rottweiler.sh
        container: qc.sec_snappy-magenta-dalmatian
  QC.Sty:
    repos:
      github.com/jkomijani/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-silver-gibbon.sh
        container: qc.sty_cloudy-xanthic-gar
  QC.Uni:
    repos:
      github.com/jkomijani/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-thistle-dugong.sh
        container: qc.uni_craggy-aqua-catfish
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-coral-husky.sh
        container: qc.ver_crabby-xanthic-squid
timeout: 5400
