config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-khaki-pig.sh
        container: qc.acc_bluesy-plum-hyena
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-gamboge-terrier.sh
        container: qc.doc_fuzzy-copper-birman
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-orange-centipede.sh
        container: qc.doc_snappy-plum-wildebeest
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-burgundy-eel.sh
        container: qc.lic_surly-platinum-chinchilla
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-auburn-tarantula.sh
        container: qc.ver_crabby-aqua-camel
timeout: 5400
