config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: snapshots
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-saffron-iguana.sh
        container: qc.acc_jumpy-jade-binturong
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cinnabar-lemming.sh
        container: qc.doc_wheezy-tangerine-okapi
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-razzmatazz-dachshund.sh
        container: qc.doc_craggy-xanthic-monkey
      github.com/jkomijani/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-tangerine-tapir.sh
        container: qc.doc_queasy-cardinal-rattlesnake
      github.com/jkomijani/normflow_ restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-purple-wolfhound.sh
        container: qc.doc_woozy-red-hornet
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cerulean-chihuahua.sh
        container: qc.lic_shabby-periwinkle-tamarin
  QC.Met:
    repos:
      github.com/jkomijani/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-white-chameleon.sh
        container: qc.met_scummy-smalt-macaw
  QC.Sec:
    repos:
      github.com/jkomijani/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cardinal-grasshopper.sh
        container: qc.sec_chewy-saffron-wildebeest
  QC.Sty:
    repos:
      github.com/jkomijani/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-malachite-mongrel.sh
        container: qc.sty_lousy-red-rhinoceros
  QC.Uni:
    repos:
      github.com/jkomijani/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-champagne-otter.sh
        container: qc.uni_cranky-brass-whale
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-seashell-jackal.sh
        container: qc.ver_flimsy-tangerine-mist
timeout: 5400
