config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ultramarine-tamarin.sh
        container: qc.acc_hilly-tan-gharial
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-periwinkle-badger.sh
        container: qc.doc_nippy-rose-bobcat
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ochre-leopard.sh
        container: qc.doc_silly-taupe-wolf
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-harlequin-wolfhound.sh
        container: qc.lic_lumpy-yellow-kakapo
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-smalt-bird.sh
        container: qc.ver_stuffy-fuchsia-capybara
timeout: 5400
