config:
  credentials: []
  project_repos:
    github.com/EOSC-Synergy-SQAaaS/normflow_:
      branch: sqaaas_with_tests
      repo: https://github.com/EOSC-Synergy-SQAaaS/normflow_
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-russet-ostrich.sh
        container: qc.acc_geeky-mauve-bat
  QC.Doc:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-red-fousek.sh
        container: qc.doc_lumpy-cinnamon-yak
      github.com/EOSC-Synergy-SQAaaS/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-bronze-fox.sh
        container: qc.doc_scummy-cardinal-angora
      github.com/EOSC-Synergy-SQAaaS/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magenta-donkey.sh
        container: qc.doc_beady-mauve-elephant
  QC.Lic:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-jade-newt.sh
        container: qc.lic_nippy-flax-moose
  QC.Met:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lime-cattle.sh
        container: qc.met_baggy-pear-gharial
  QC.Sec:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-jade-argentino.sh
        container: qc.sec_crabby-lilac-crocodile
  QC.Sty:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ruby-woodpecker.sh
        container: qc.sty_whiny-turquoise-chipmunk
  QC.Uni:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-coral-cuttlefish.sh
        container: qc.uni_chewy-linen-ibis
  QC.Ver:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-lemon-chipmunk.sh
        container: qc.ver_tasty-cornflower-wolf
timeout: 5400
