config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-buff-hyena.sh
        container: qc.acc_tacky-lilac-chin
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-denim-camel.sh
        container: qc.doc_hilly-asparagus-newt
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-amaranth-ladybird.sh
        container: qc.doc_surly-amaranth-whippet
      github.com/jkomijani/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-black-dhole.sh
        container: qc.doc_breezy-ecru-dhole
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-orchid-cuttlefish.sh
        container: qc.lic_flimsy-cerise-tuatara
  QC.Met:
    repos:
      github.com/jkomijani/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-teal-mastiff.sh
        container: qc.met_woozy-indigo-barb
  QC.Sec:
    repos:
      github.com/jkomijani/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-viridian-abyssinian.sh
        container: qc.sec_scummy-cobalt-wolfhound
  QC.Sty:
    repos:
      github.com/jkomijani/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-silver-bonobo.sh
        container: qc.sty_flaky-sepia-albatross
  QC.Uni:
    repos:
      github.com/jkomijani/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-charcoal-kudu.sh
        container: qc.uni_muzzy-harlequin-tarsier
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-auburn-dogfish.sh
        container: qc.ver_silly-rust-zebu
timeout: 5400
