config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lime-urchin.sh
        container: qc.acc_dorky-cornflower-chow
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pear-heron.sh
        container: qc.doc_sunny-pumpkin-tarsier
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cornflower-moose.sh
        container: qc.doc_surly-razzmatazz-chinook
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-violet-wolfhound.sh
        container: qc.lic_geeky-tangerine-cassowary
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-brass-spider.sh
        container: qc.ver_shaky-pear-giraffe
timeout: 5400
