config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-yellow-giraffe.sh
        container: qc.acc_stinky-silver-dugong
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-lavender-drever.sh
        container: qc.doc_pasty-lilac-elephant
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-malachite-guppy.sh
        container: qc.doc_stealthy-heliotrope-fossa
      github.com/jkomijani/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-malachite-dingo.sh
        container: qc.doc_sunny-zucchini-dingo
      github.com/jkomijani/normflow_ restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-apricot-cuscus.sh
        container: qc.doc_grumpy-dandelion-setter
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-crimson-husky.sh
        container: qc.lic_thirsty-blue-lizard
  QC.Met:
    repos:
      github.com/jkomijani/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-white-starfish.sh
        container: qc.met_lovely-bistre-budgerigar
  QC.Sec:
    repos:
      github.com/jkomijani/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-lime-squirt.sh
        container: qc.sec_homely-purple-termite
  QC.Sty:
    repos:
      github.com/jkomijani/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-linen-buffalo.sh
        container: qc.sty_shaggy-amethyst-schnauzer
  QC.Uni:
    repos:
      github.com/jkomijani/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-fuchsia-grasshopper.sh
        container: qc.uni_surly-harlequin-mandrill
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-magenta-mandrill.sh
        container: qc.ver_squeaky-salmon-spider
timeout: 5400
