config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-gamboge-wallaby.sh
        container: qc.acc_trippy-sangria-crane
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pink-kakapo.sh
        container: qc.doc_bluesy-linen-bat
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-pear-hyena.sh
        container: qc.doc_scaly-pink-boar
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-buff-booby.sh
        container: qc.lic_scummy-rose-lizard
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-scarlet-maltese.sh
        container: qc.ver_snoopy-cobalt-uguisu
timeout: 5400
