config:
  credentials: []
  project_repos:
    github.com/EOSC-Synergy-SQAaaS/normflow_:
      branch: sqaaas_with_tests
      repo: https://github.com/EOSC-Synergy-SQAaaS/normflow_
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-russet-iguana.sh
        container: qc.acc_skimpy-carmine-ladybird
  QC.Doc:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-myrtle-cattle.sh
        container: qc.doc_tasty-saffron-chinchilla
      github.com/EOSC-Synergy-SQAaaS/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-linen-mule.sh
        container: qc.doc_cloudy-seashell-yak
      github.com/EOSC-Synergy-SQAaaS/normflow_ markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amethyst-caracal.sh
        container: qc.doc_chewy-cardinal-dugong
  QC.Lic:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-saffron-panda.sh
        container: qc.lic_snippy-amaranth-booby
  QC.Met:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cobalt-javanese.sh
        container: qc.met_bluesy-periwinkle-cat
  QC.Sec:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-blue-bloodhound.sh
        container: qc.sec_chummy-chocolate-eel
  QC.Sty:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-gamboge-balinese.sh
        container: qc.sty_crabby-zucchini-coati
  QC.Uni:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ pytest:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-khaki-frog.sh
        container: qc.uni_snazzy-sepia-neanderthal
  QC.Ver:
    repos:
      github.com/EOSC-Synergy-SQAaaS/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-alizarin-insect.sh
        container: qc.ver_stuffy-orchid-earwig
timeout: 5400
