config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jkomijani/normflow_:
      branch: normflow_public_v1.1
      repo: https://github.com/jkomijani/normflow_
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-olivine-hedgehog.sh
        container: qc.acc_gummy-lavender-okapi
  QC.Doc:
    repos:
      github.com/jkomijani/normflow_ find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-amber-tzu.sh
        container: qc.doc_cozy-green-bongo
      github.com/jkomijani/normflow_ git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-chocolate-retriever.sh
        container: qc.doc_crabby-teal-heron
  QC.Lic:
    repos:
      github.com/jkomijani/normflow_ licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-olive-panda.sh
        container: qc.lic_droopy-ultramarine-tortoise
  QC.Ver:
    repos:
      github.com/jkomijani/normflow_ get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amaranth-hedgehog.sh
        container: qc.ver_ready-black-snail
timeout: 5400
